version: "3.3"
services:
  app:
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $APP_PORT:$APP_PORT
    environment:
      - DB_HOST=postgres
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true
volumes:
  db: